/* 
 * File:   main.cpp
 * Author:Fernando Martinez 
 * Created on June 25, 2015, 4:34 PM
 * Purpose: Sales Prediction 
 */

#include <iostream>
using namespace std;

//User Libraries 

//Global Constants 

//Function Prototypes
//Execution Begins Here!
int main(int argc, char** argv) {
    float SdC,TsC,GC;
    TsC=4.6e6; // Total Sales Revenue 
    SdC=.62; // East Coast Divisions percent Generated 
    GC=(TsC*SdC); // The Predicted Amount of money the East Coast sales Division made.
    //Output Products 
    cout<<"The total Money Generated by the East Coast is ="<<(GC)<<endl;

    return 0;
}

